version: '3.8'

services:
  db:
    image: postgres:15
    container_name: reserva_espacios_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reserva_espacios_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: reserva_espacios_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    networks:
      - reserva_espacios_network
    depends_on:
      - db

networks:
  reserva_espacios_network:
    driver: bridge

volumes:
  postgres_data: